// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace aspMvcExercise.Models
{
    [Table("Proizvod")]
    public partial class Proizvod
    {
        [Key]
        public int ProizvodId { get; set; }

        [Required(ErrorMessage = "Unesi kategoriju")]
        public int KategorijaId { get; set; }

        [Required(ErrorMessage = "Unesi naziv")]
        [StringLength(50, ErrorMessage = "Maksimalno 50 karaktera")]
        [Display(Name = "Naziv")]
        public string NazivProizvoda { get; set; }

        [Required(ErrorMessage = "Unesi cijenu")]
        [Column(TypeName = "decimal(12, 3)")]
        public decimal Cijena { get; set; }

       [Required (ErrorMessage = "Unesi kolicinu")]
        [Display(Name = "Kolicina")]
        public int KolicinaNaLageru { get; set; }

        [ForeignKey(nameof(KategorijaId))]
        [InverseProperty("Proizvodi")]
        public virtual Kategorija Kategorija { get; set; }
    }
}